apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    name: react-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32760
  selector:
    name: react-pod
    app: demo-voting-app