
#Services

# 1. NodePort
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    tier: frontend
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: myapp
    tier: frontend

# 2. ClusterIp

apiVersion: v1
kind: Service
metadata:
   name: myapp-service
   labels:
    app: myapp
    tier: frontend

spec:
  type: ClusterIp
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: myapp
    tier: frontend

  