apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    tier: frontend
spec:
   template:
     metadata:
       name: myapp-pod
       labels:
         app: myapp
         tier: frontend
     spec:
        containers:
          - name: react
            image: dayakar13/react:latest
   replicas: 6
   selector:
      matchLabels:
        tier: frontend



  