apiVersion: v1
kind: Pod
metadata:
  name: voter-pod
  labels:
    name: voter-pod
    app: demo-voting-app
spec:
  containers:
    - name: voter-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
     
        

