apiVersion: v1
kind: Service
metadata:
  name: voter-service
  labels:
    name: voter-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32764
      targetPort: 80
  selector:
    name: voter-pod
    app: demo-voting-app
